server:
  port: 1525

---
server:
  port: 1525

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---