server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healing-db?serverTimezone=Asia/Seoul
    username: test
    password: password
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true