version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    #      - "3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'healing-db'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: Asia/Seoul
